# This file was generated by GoReleaser. DO NOT EDIT.
cask "docket" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "9ddf80f05f7b15eb5b2599a0c7afc34353c0159e8867599813dcd7a4f4767629"
      url "https://github.com/incantery/docket/releases/download/v#{version}/docket_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c5b428c422c1c941e2e2905366dd9b21b60d4a9ce80442948443a3b0d47f183b"
      url "https://github.com/incantery/docket/releases/download/v#{version}/docket_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "docket"
  desc "The list: what is still to do, as a Markdown checklist and a log, for people and programs"
  homepage "https://github.com/incantery/docket"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docket"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docket"]
    end
  end

  # No zap stanza required
end
