# This file was generated by GoReleaser. DO NOT EDIT.
cask "docket" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "57e5912aeb9d7a45c59342433d3113ac5ee4ed8538345c6bce302a43eead3b1f"
      url "https://github.com/incantery/docket/releases/download/v#{version}/docket_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d683507204de5189ce8d0f250f85c1a72bfdde604bd5142fd4ad63627353330f"
      url "https://github.com/incantery/docket/releases/download/v#{version}/docket_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "docket"
  desc "The list: what is still to do, as a Markdown checklist and a log, for people and programs"
  homepage "https://github.com/incantery/docket"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docket"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docket"]
    end
  end

  # No zap stanza required
end
