# This file was generated by GoReleaser. DO NOT EDIT.
cask "grim" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "b5c833f220235c1e018008f411765e7f882c2a7d7c8a118ed64af6a09accef12"
      url "https://github.com/incantery/grimoire/releases/download/v#{version}/grim_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6732f1dcffa223e5d0b05c08389bfebabd527af163f2bcea975540caf7e8deb9"
      url "https://github.com/incantery/grimoire/releases/download/v#{version}/grim_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "grim"
  desc "An agent that is already there: summoned in a popup over rook or tmux, it looks around, acts through tools, and keeps going"
  homepage "https://github.com/incantery/grimoire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grim"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grim"]
    end
  end

  # No zap stanza required
end
