# This file was generated by GoReleaser. DO NOT EDIT.
cask "grove" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "fb49d7afa7b9877a55b9e33e619e326c43f7b5831d3cf79fa32cf39ae8f7e430"
      url "https://github.com/incantery/grove/releases/download/v#{version}/grove_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cde5cd735fea11c98f718a0a5b930374eb2465d12b15ad0bbd912d9f1418e118"
      url "https://github.com/incantery/grove/releases/download/v#{version}/grove_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "grove"
  desc "One git worktree per task, and the place you work in it: rook, tmux, or none"
  homepage "https://github.com/incantery/grove"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grove"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grove"]
    end
  end

  # No zap stanza required
end
