# This file was generated by GoReleaser. DO NOT EDIT.
cask "grove" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "83e33652b688db1969e8b3c88de6cb2c8715cf1988f59ca0a619b193cbff9664"
      url "https://github.com/incantery/grove/releases/download/v#{version}/grove_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8790c36a63e0b5f57ef888ebcc2c7fcefa28fda6f8c12dda0f95ca37321da908"
      url "https://github.com/incantery/grove/releases/download/v#{version}/grove_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "grove"
  desc "One git worktree per task, and the place you work in it: rook, tmux, or none"
  homepage "https://github.com/incantery/grove"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grove"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grove"]
    end
  end

  # No zap stanza required
end
