# This file was generated by GoReleaser. DO NOT EDIT.
cask "mote" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7a731dc011a7806ec11ca32130a140dff9c183b46ffbfa689309d5649a3069d6"
      url "https://github.com/incantery/mote/releases/download/v#{version}/mote_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6283e378422cff51f049aeb8f679444b91b066eaffbd48564ef5c5ef895ee558"
      url "https://github.com/incantery/mote/releases/download/v#{version}/mote_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "mote"
  desc "A small agent harness: a loop over a model with tools, a record, and a terminal to watch it in"
  homepage "https://github.com/incantery/mote"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mote"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mote"]
    end
  end

  # No zap stanza required
end
