# This file was generated by GoReleaser. DO NOT EDIT.
cask "rook" do
  version "0.51.0"

  on_macos do
    on_arm do
      sha256 "e778f9d12ed6e473f65d7352ff2b2e62313fbd7cdf2c7a518e4ddaf4ddda868c"
      url "https://github.com/incantery/rook/releases/download/v#{version}/rook_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03b84faf889156aef51db75188bbe982d380ddd75388769b1f39f59053ec8c27"
      url "https://github.com/incantery/rook/releases/download/v#{version}/rook_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "rook"
  desc "Terminal multiplexer and attention layer for many terminal-agent sessions"
  homepage "https://github.com/incantery/rook"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "bin/rook"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/rook", "#{staged_path}/libexec/rook/engine"]
    end
  end

  # No zap stanza required
end
