# This file was generated by GoReleaser. DO NOT EDIT.
cask "rook" do
  version "0.55.0"

  on_macos do
    on_arm do
      sha256 "024556bc044c13735e61a3a1052a577a49f1e390c840fc926a79d3f369af633c"
      url "https://github.com/incantery/rook/releases/download/v#{version}/rook_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "beee96638d9816e2d1efb91aeabff516a6f56a592de19071856a96a8018bd1c8"
      url "https://github.com/incantery/rook/releases/download/v#{version}/rook_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "rook"
  desc "Terminal multiplexer and attention layer for many terminal-agent sessions"
  homepage "https://github.com/incantery/rook"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "bin/rook"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/rook", "#{staged_path}/libexec/rook/engine"]
    end
  end

  # No zap stanza required
end
