# This file was generated by GoReleaser. DO NOT EDIT.
cask "rook" do
  version "0.50.1"

  on_macos do
    on_arm do
      sha256 "116fb8142ec458fdd55e14c259f83419feb7138f8c199c889e3ac6a1a422d6a1"
      url "https://github.com/incantery/rook/releases/download/v#{version}/rook_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f2061c416bd4edf93c26aeae4ffe3cadc24b17b0d4aff09708ef9f5e48225a5"
      url "https://github.com/incantery/rook/releases/download/v#{version}/rook_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "rook"
  desc "Terminal multiplexer and attention layer for many terminal-agent sessions"
  homepage "https://github.com/incantery/rook"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "bin/rook"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/rook", "#{staged_path}/libexec/rook/engine"]
    end
  end

  # No zap stanza required
end
