# This file was generated by GoReleaser. DO NOT EDIT.
cask "usage" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "df15ef8d42f1b40ed985c4f80b2527f0a0b602a62837dd51e121fad9e433663c"
      url "https://github.com/incantery/usage/releases/download/v#{version}/usage_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d75b754f960dec864b8c0e9ca29a06b2e5660fbf9312dfb83a333169fb0778a"
      url "https://github.com/incantery/usage/releases/download/v#{version}/usage_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "usage"
  desc "Reports how much of a coding assistant's metered allowance is gone, for people and programs"
  homepage "https://github.com/incantery/usage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usage"
  binary "usage-tui"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/usage"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/usage-tui"]
    end
  end

  # No zap stanza required
end
