# This file was generated by GoReleaser. DO NOT EDIT.
cask "usage" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "a12e30c468a704c53839cde246d8a6d43e4e6c8ecf5c5eeeea8697a48e970d1d"
      url "https://github.com/incantery/usage/releases/download/v#{version}/usage_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "be5e5fa4f692e0da29e7f8d1348944ab9d30ea0e58438cab419cb70d9e89b2a9"
      url "https://github.com/incantery/usage/releases/download/v#{version}/usage_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "usage"
  desc "Reports how much of a coding assistant's metered allowance is gone, for people and programs"
  homepage "https://github.com/incantery/usage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "usage"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/usage"]
    end
  end

  # No zap stanza required
end
