# This file was generated by GoReleaser. DO NOT EDIT.
cask "vera" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "607667f762a851bbfd10dd59f74655ce1404e7bb10fe8c4c3d1c58ec2aa0f519"
      url "https://github.com/incantery/vera/releases/download/v#{version}/vera_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5beb7908dd93d60e1be7e94402f701d0e7f9109fe255ed34acbb31a4d0621e5c"
      url "https://github.com/incantery/vera/releases/download/v#{version}/vera_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "vera"
  desc "Persistent assistant between your phone and your Mac: vera CLI and verad daemon"
  homepage "https://github.com/incantery/vera"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bin/vera"
  binary "bin/verad"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/vera", "#{staged_path}/bin/verad"]
    end
  end

  # No zap stanza required
end
