# This file was generated by GoReleaser. DO NOT EDIT.
cask "vera" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "ab4d0c8ee7ce74e68fd9705f2516e8d24c4ec0db31e42a81acc6ac0c7cec42be"
      url "https://github.com/incantery/vera/releases/download/v#{version}/vera_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b242f0d187ba016c1e1d886ae59756e1560114a60bf82ee7cdbeb9d2aabf8f46"
      url "https://github.com/incantery/vera/releases/download/v#{version}/vera_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "vera"
  desc "Persistent assistant between your phone and your Mac: vera CLI and verad daemon"
  homepage "https://github.com/incantery/vera"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bin/vera"
  binary "bin/verad"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/vera", "#{staged_path}/bin/verad"]
    end
  end

  # No zap stanza required
end
