# This file was generated by GoReleaser. DO NOT EDIT.
cask "vera" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "f0645faa8b393f63a930248e823b2c68ef497b3c5787f61988ffd9ee89521c67"
      url "https://github.com/incantery/vera/releases/download/v#{version}/vera_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "010fd146d7ffbc35e3ca5e56d982bde462503e017d89bb08ce200e2991d9a1c2"
      url "https://github.com/incantery/vera/releases/download/v#{version}/vera_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "vera"
  desc "Persistent assistant between your phone and your Mac: vera CLI and verad daemon"
  homepage "https://github.com/incantery/vera"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bin/vera"
  binary "bin/verad"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bin/vera", "#{staged_path}/bin/verad"]
    end
  end

  # No zap stanza required
end
